base_path: /Users/sekiguchi/ai-services/Models/

checkpoints: checkpoints/
vae: vae/
loras: loras/
upscale_models: upscale_models/
embeddings: embeddings/
controlnet: controlnet/
clip_vision: clip_vision/
style_models: style_models/